version: '3.3'
services:
  php:
    build: ./docker/php
    container_name: test_php
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"

  nginx:
    image: nginx:latest
    container_name: test_nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/config:/etc/nginx/conf.d

  composer:
    image: composer:latest
    command: [ 'validate' ]
    volumes:
      - ./:/app