version: '3.3'
services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/config:/etc/nginx/conf.d

  composer:
    image: composer:latest
    command: [ 'validate' ]
    volumes:
      - ./:/app